import type { Question, StudyUnit } from "../data";

export const saniUnits: StudyUnit[] = [
  { id: "u1", name: "Unidad 1 · Fundamentos y salud colectiva", pages: [1, 20] },
  { id: "u2", name: "Unidad 2 · Estado, políticas y derechos", pages: [21, 61] },
  { id: "u3", name: "Unidad 3 · Diagnóstico y epidemiología", pages: [62, 77] },
  { id: "u4", name: "Unidad 4 · Promoción y salud mental comunitaria", pages: [78, 87] },
  { id: "u5", name: "Unidad 5 · Intervención y planificación", pages: [88, 107] }
];

export const saniTopics = [
  "Salud colectiva y paradigmas", "Interdisciplina y equidad",
  "Estado y sistema de salud", "APS y derechos", "Diagnóstico comunitario",
  "Epidemiología", "Promoción y prevención", "Salud mental comunitaria",
  "Intervención psicológica", "Planificación y evaluación", "Integración final"
];

type Unit = "u1" | "u2" | "u3" | "u4" | "u5";
type Pages = [number, number];
type WrittenType = "development" | "case-study" | "flashcard" | "image-analysis";
const [fund, equity, state, rights, diagnosis, epi, promotion, community, intervention, planning, integration] = saniTopics;

function base(id: string, unit: Unit, topic: string, pages: Pages, prompt: string, explanation: string) {
  return { id: `sani-${id}`, subjectId: "sani", unit, topic, prompt, explanation,
    sourcePages: pages, source: `Sani Final PDF, unidad ${unit.slice(1)}, ${pages[0] === pages[1] ? `p. ${pages[0]}` : `pp. ${pages[0]}–${pages[1]}`} (numeración del archivo).` };
}
function c(id: string, unit: Unit, topic: string, pages: Pages, prompt: string, options: string[], answer: number, explanation: string): Question {
  return { ...base(id, unit, topic, pages, prompt, explanation), type: "choice", difficulty: "Base", options, answer };
}
function t(id: string, unit: Unit, topic: string, pages: Pages, prompt: string, answer: boolean, explanation: string): Question {
  return { ...base(id, unit, topic, pages, prompt, explanation), type: "true-false", difficulty: "Aplicación", options: ["Verdadero", "Falso"], answer: answer ? 0 : 1 };
}
function w(id: string, unit: Unit, topic: string, pages: Pages, type: WrittenType, prompt: string, explanation: string, rubric: string[]): Question {
  return { ...base(id, unit, topic, pages, prompt, explanation), type, difficulty: type === "flashcard" ? "Base" : "Aplicación", rubric };
}

const unit1: Question[] = [
  c("objeto", "u1", fund, [1, 2], "¿Cuál es el objeto de estudio e intervención de la Psicología Sanitaria en el resumen?", ["La enfermedad individual separada del contexto", "La salud humana como proceso colectivo", "La gestión exclusiva de hospitales psiquiátricos", "La conducta observable sin dimensiones subjetivas"], 1, "El objeto es la salud humana como proceso colectivo. La vida cotidiana constituye un campo de trabajo donde se articulan dimensiones materiales, simbólicas, sociales y subjetivas."),
  c("conflicto", "u1", fund, [1, 5], "Desde la perspectiva dialéctica presentada, ¿qué caracteriza lo patológico?", ["La existencia de cualquier conflicto", "La participación en transformaciones sociales", "El bloqueo del conflicto y la imposibilidad de resolverlo", "La presencia de diferencias entre sujetos"], 2, "El conflicto forma parte de la vida. El resumen ubica lo patológico en su bloqueo e imposibilidad de resolución, no en el conflicto por sí mismo."),
  c("nucleo-campo", "u1", equity, [6, 7], "En la propuesta de Campos, ¿qué diferencia al núcleo del campo?", ["Núcleo: competencias específicas; campo: saberes y responsabilidades compartidos", "Núcleo: edificio; campo: territorio geográfico", "Núcleo: tareas de todas las profesiones; campo: exclusividad médica", "Núcleo y campo eliminan toda responsabilidad profesional"], 0, "El núcleo conserva la especificidad de cada profesión. El campo permite compartir conocimientos y responsabilidades mediante acuerdos, sin borrar la autonomía profesional."),
  c("equidad", "u1", equity, [8, 9], "¿Qué asignación de recursos expresa mejor la equidad en salud?", ["Asignar idénticos recursos aunque las necesidades sean diferentes", "Asignar recursos según la capacidad de pago", "Concentrar todos los recursos en la atención especializada", "Distribuir los recursos considerando necesidades y desventajas sociales"], 3, "La equidad se vincula con justicia social y derechos: busca que la posición social no impida desarrollar el potencial de salud y exige atender diferencias de necesidad."),
  c("upstream", "u1", equity, [9, 10], "Una política modifica la distribución de ingresos y la estratificación social. ¿En qué nivel de la cadena causal interviene?", ["Downstream, sobre consecuencias del daño", "Upstream, sobre determinantes estructurales", "Midstream, exclusivamente sobre hábitos personales", "Solo en rehabilitación individual"], 1, "Upstream actúa sobre el contexto y la estratificación. Midstream aborda condiciones y estilos de vida; downstream reduce las consecuencias de desigualdades en salud."),
  c("colectiva", "u1", fund, [18, 20], "Según la presentación de Casallas, ¿qué caracteriza a la medicina social/salud colectiva latinoamericana?", ["Toma como único objeto el cuerpo biológico", "Explica la salud exclusivamente por elecciones personales", "Estudia necesidades sociales de salud y procesos históricos de determinación", "Reduce la intervención a técnicas hospitalarias descontextualizadas"], 2, "Esta perspectiva sitúa las necesidades sociales y la reproducción social en el centro del análisis. Integra historia, relaciones sociales, organización de servicios y praxis."),
  t("sincronia", "u1", fund, [1, 1], "La mirada sincrónica examina interacciones actuales; la diacrónica incorpora la construcción histórica del proceso salud-enfermedad.", true, "Son perspectivas complementarias: una permite leer las relaciones presentes y la otra su formación y transformación en el tiempo."),
  t("muchas-profesiones", "u1", equity, [3, 7], "Reunir profesionales de distintas disciplinas garantiza, por sí solo, un trabajo interdisciplinario.", false, "La interdisciplina exige intercambio, un objeto y una tarea compartidos, negociación de responsabilidades y revisión de las relaciones de poder. La mera coexistencia no basta."),
  t("gradiente", "u1", equity, [8, 10], "El gradiente social de salud se limita a distinguir entre personas indigentes y el resto de la población.", false, "El gradiente recorre la escala social. Por eso el texto propone estrategias poblacionales y no únicamente intervenciones sobre los grupos más desfavorecidos."),
  w("complejidad", "u1", fund, [1, 3], "development", "Explicá por qué la Psicología Sanitaria busca superar las dicotomías mente/cuerpo y sujeto/contexto.", "La salud se construye en relaciones biológicas, subjetivas y sociales. La vida cotidiana articula condiciones materiales, procesos de socialización y sentidos. Una intervención integral necesita considerar esa trama y sus determinaciones históricas, en lugar de aislar un polo.", ["Integra lo biológico, social y subjetivo.", "Relaciona vida cotidiana y determinaciones históricas.", "Deriva una consecuencia para la intervención interdisciplinaria o intersectorial."]),
  w("modelos-determinacion", "u1", fund, [12, 14], "development", "Compará el modelo de anillos de Dahlgren y Whitehead con los niveles de vida cotidiana presentados a partir de Castellanos.", "Los anillos relacionan factores individuales, estilos de vida, redes, condiciones de vida y trabajo y contexto socioeconómico, cultural y ambiental. Castellanos diferencia modo de vida general, condiciones de vida particulares y estilos de vida singulares. Ambos permiten relacionar escalas sin aislar los factores biológicos de su contexto.", ["Describe las capas del modelo de anillos.", "Distingue los niveles general, particular y singular.", "Explica relaciones entre niveles; no los trata como factores independientes."]),
  w("tutelar-derechos", "u1", fund, [15, 17], "development", "Compará el modelo tutelar con el paradigma de derechos en salud mental tal como se presentan en el resumen.", "El modelo tutelar se organiza alrededor de incapacidad, segregación, beneficencia y asimetrías. El paradigma de derechos destaca capacidad, autonomía, apoyos, inclusión comunitaria e interdisciplina. El cambio enfrenta intereses y relaciones de poder dentro del campo, por lo que no se agota en cambiar una definición.", ["Contrasta la posición del sujeto en ambos modelos.", "Incluye autonomía, apoyos e inclusión.", "Relaciona la transformación con luchas e intereses del campo."]),
  w("caso-ausencias", "u1", equity, [8, 11], "case-study", "Caso ficticio: un centro atribuye las ausencias a turnos a la 'falta de interés'. Las personas reportan horarios laborales incompatibles y transporte costoso. Analizá el problema con los determinantes sociales y proponé dos líneas de acción.", "Hay que explorar condiciones de trabajo, ingresos, transporte y organización del servicio antes de culpabilizar a las personas. Son pertinentes ajustes de horarios acordados con usuarios y articulación con actores de transporte o trabajo. Conviene diferenciar medidas sobre barreras inmediatas y sobre condiciones estructurales.", ["Identifica determinantes sociales concretos.", "Evita reducir las ausencias a falta de voluntad.", "Propone dos acciones y participación de las personas afectadas."]),
  w("caso-equipo", "u1", equity, [6, 7], "case-study", "Caso ficticio: un equipo reúne medicina, psicología y trabajo social, pero una sola profesión decide todas las acciones. ¿Qué cambiarías para construir interdisciplina?", "La composición multiprofesional debe traducirse en una tarea común, intercambio de saberes y acuerdos sobre campo y núcleos. El liderazgo puede variar según el problema. También hay que trabajar los obstáculos vinculados al conocimiento y a las posiciones subjetivas y de poder.", ["Distingue multiprofesionalidad de interdisciplina.", "Propone acuerdos de responsabilidades sin borrar especificidades.", "Incluye revisión del liderazgo y trabajo sobre obstáculos."]),
  w("oral-salud", "u1", fund, [1, 2], "flashcard", "Explicá en voz alta: objeto, campo de trabajo y tres dimensiones de la Psicología Sanitaria.", "Objeto: salud humana como proceso colectivo. Campo de trabajo: vida cotidiana. Dimensiones articuladas: biológica, social y subjetiva, dentro de condiciones políticas, económicas e históricas.", ["Nombra el proceso colectivo y la vida cotidiana.", "Articula las dimensiones en lugar de enumerarlas sin relación."]),
  w("oral-participacion", "u1", equity, [10, 11], "flashcard", "Ordená oralmente las modalidades de participación: consulta, información, colaboración, empoderamiento e implicación.", "De menor a mayor implicación: información, consulta, implicación, colaboración y empoderamiento. La diferencia decisiva es el poder real de la comunidad sobre las decisiones, no solo su presencia en reuniones.", ["Ordena las cinco modalidades.", "Explica el vínculo entre participación y distribución del poder."]),
  { ...w("imagen-niveles", "u1", fund, [13, 14], "image-analysis", "Observá el esquema. Relacioná A, B y C con los niveles general, particular y singular de Castellanos y explicá una relación entre ellos.", "A corresponde al modo de vida general; B, a las condiciones de vida de grupos particulares; C, a los estilos de vida singulares. Las decisiones cotidianas están relacionadas con condiciones de trabajo y recursos, dentro de una organización socioeconómica y política. El esquema simplifica relaciones que son dinámicas.", ["Relaciona correctamente los tres niveles.", "Explica una mediación entre condiciones y prácticas.", "No reduce la salud a una elección individual."]), media: { type: "image", src: "/images/sani-niveles.svg", alt: "Tres recuadros conectados: A, organización socioeconómica y política; B, condiciones de vida y trabajo de grupos; C, prácticas cotidianas de personas.", width: 900, height: 540, caption: "Esquema didáctico elaborado a partir de las pp. 13–14. No es una figura original del PDF." } }
];

const unit2: Question[] = [
  c("foucault", "u2", state, [21, 22], "¿Qué secuencia de medicina social presenta el resumen a partir de Foucault?", ["Medicina privada, hospitalaria y genética", "Medicina urbana, molecular y de precisión", "Medicina de Estado, urbana y de la fuerza de trabajo", "Medicina comunitaria, individual y exclusivamente comercial"], 2, "La secuencia presentada vincula la medicina de Estado con Alemania/Prusia, la urbana con Francia y la de la fuerza de trabajo con Inglaterra. Expresa formas de intervención social sobre cuerpos y poblaciones."),
  c("desmercantilizacion", "u2", state, [22, 23], "¿Qué significa desmercantilización en el análisis del bienestar?", ["Poder sostener condiciones de vida sin depender completamente de la participación en el mercado", "Eliminar todas las instituciones estatales", "Convertir los derechos sociales en bienes de compra", "Restringir la asistencia a quienes pueden pagarla"], 0, "La desmercantilización refiere al acceso a un nivel de vida aceptable independientemente del mercado. Permite comparar cómo los regímenes de bienestar protegen derechos y subsistencia."),
  c("estrategias-neoliberales", "u2", state, [23, 25], "¿Qué conjunto reúne las cuatro estrategias neoliberales descriptas en el resumen?", ["Universalización, gratuidad, igualdad y expansión de derechos", "Centralización, estatización, universalización y redistribución", "Interdisciplina, promoción, prevención y rehabilitación", "Recorte del gasto social, privatización, focalización y descentralización"], 3, "El texto enumera esas cuatro estrategias en su análisis del proyecto neoliberal. La respuesta refiere a esa caracterización histórica, no a que toda descentralización tenga necesariamente el mismo sentido político."),
  c("aps-integral", "u2", rights, [26, 28], "¿Qué distingue a la APS integral de entender la APS solo como primer nivel?", ["La APS integral excluye hospitales y especialistas", "Organiza el conjunto del sistema y vincula atención, participación y determinantes sociales", "Se limita a un paquete de prestaciones para grupos de riesgo", "Sustituye toda atención por campañas informativas"], 1, "El primer nivel es una puerta de entrada. La APS como estrategia integral orienta todo el sistema, sus articulaciones y la construcción de ciudadanía y del derecho a la salud."),
  c("capital-simbolico", "u2", state, [38, 39], "En el análisis de Spinelli, ¿qué capital se vincula con imponer significaciones de forma legítima?", ["Económico", "Social", "Simbólico", "Infraestructural"], 2, "El capital simbólico refiere al reconocimiento y a la capacidad de imponer significaciones legítimas. El campo incluye también capital económico, social y cultural y sus disputas."),
  c("diagnostico-capacidad", "u2", rights, [40, 41], "Según la presentación de la Ley 26.657 en el PDF, ¿qué permite concluir por sí solo un diagnóstico de salud mental?", ["Incapacidad permanente", "Necesidad automática de internación", "Peligrosidad para otras personas", "No autoriza por sí solo a presumir riesgo de daño o incapacidad"], 3, "El resumen distingue diagnóstico de evaluación del riesgo o de la capacidad. Rechaza que una etiqueta diagnóstica determine automáticamente incapacidad o peligrosidad."),
  c("subsectores", "u2", state, [52, 54], "¿Qué asociación entre subsistema y financiamiento corresponde al esquema del resumen?", ["Público: rentas generales; seguridad social: aportes y contribuciones; privado voluntario: cuotas", "Público: solo cuotas; seguridad social: solo donaciones; privado: solo impuestos", "Los tres tienen idéntico financiamiento y afiliación", "Seguridad social: exclusivamente pago por consulta"], 0, "El esquema distingue fuentes de financiamiento y formas de cobertura. El texto advierte que los vínculos reales son complejos, superpuestos y fragmentados."),
  c("barreras", "u2", rights, [56, 57], "Un servicio existe en el barrio pero atiende solo en horarios incompatibles con el trabajo de sus usuarios. ¿Qué barrera ilustra principalmente?", ["Exclusivamente geográfica", "Administrativa u organizativa", "Ausencia de una enfermedad específica", "Una prueba suficiente de desinterés individual"], 1, "La disponibilidad física no asegura acceso. Los horarios y la organización pueden bloquearlo, junto con barreras culturales, geográficas y de capacidad resolutiva."),
  t("medicina-social", "u2", state, [21, 22], "En la lectura de Foucault presentada, la medicina moderna se entiende como práctica social y tecnología de intervención sobre los cuerpos.", true, "El análisis vincula medicina, control social, cuerpo y Estado. No identifica el carácter social únicamente con una relación comercial médico-paciente."),
  t("derechos-escritos", "u2", rights, [46, 48], "El reconocimiento escrito de un derecho basta para garantizar su ejercicio efectivo.", false, "El resumen diferencia reconocimiento y cumplimiento. Hacen falta políticas públicas, recursos y posibilidades reales de ejercer y reclamar derechos."),
  t("at-aislado", "u2", rights, [43, 44], "Según el apartado de acompañamiento terapéutico, el AT debe actuar como un servicio aislado e independiente del equipo tratante.", false, "El resumen sitúa al AT dentro de un marco interdisciplinario, con supervisión y coordinación de profesionales tratantes. Su intervención se inscribe en una estrategia terapéutica."),
  t("aps-valores", "u2", rights, [55, 57], "La APS renovada del resumen se apoya en derecho a la salud, equidad y solidaridad.", true, "Esos valores se articulan con calidad, participación, intersectorialidad y responsabilidad de los gobiernos ante las necesidades de la población."),
  w("bienestar-genero", "u2", state, [22, 25], "development", "Explicá la crítica feminista a los análisis del bienestar centrados solo en Estado y mercado.", "Esos análisis pueden invisibilizar el trabajo doméstico y de cuidados no remunerado, históricamente realizado por mujeres. Incorporar familia y comunidad permite examinar quién produce bienestar, cómo se distribuyen las cargas y qué desigualdades quedan ocultas.", ["Reconoce el trabajo de cuidados no remunerado.", "Explica el sesgo del varón proveedor.", "Incorpora familia y comunidad al análisis."]),
  w("campo-sistema", "u2", state, [38, 39], "development", "¿Qué agrega el concepto de campo de la salud a una descripción que solo enumera subsistemas?", "Permite analizar actores, intereses, recursos, capitales y relaciones de poder. Las posiciones se disputan mediante acuerdos y conflictos, por lo que no basta representar al sector como un sistema funcionalmente integrado.", ["Identifica actores y capitales.", "Explica relaciones de fuerza y hegemonía.", "Relaciona esas disputas con acceso, gestión o distribución de recursos."]),
  w("reforma-dispositivos", "u2", rights, [29, 32], "development", "Explicá por qué la desinstitucionalización requiere construir dispositivos y redes de cuidado.", "La sustitución de la lógica asilar exige respuestas comunitarias, servicios de salud mental en hospitales generales y articulación con el primer nivel. El resumen menciona centros de día, casas de convivencia y alternativas laborales. Cerrar o dar altas sin apoyos no garantiza inclusión ni continuidad de cuidados.", ["Distingue desinstitucionalización de simple cierre o alta.", "Propone dispositivos comunitarios del resumen.", "Incluye continuidad de cuidados e inclusión social."]),
  w("derechos-circulo", "u2", rights, [58, 61], "development", "Reconstruí el círculo entre vulneración de derechos sociales y padecimiento mental que presenta Yoma.", "La falta de vivienda, trabajo y protección social puede producir sufrimiento y obstaculizar la externación. El estigma y la institucionalización dificultan a su vez acceder a esos derechos. Romper el círculo exige políticas integrales e intersectoriales y considerar las relaciones económicas que reproducen la exclusión.", ["Explica ambos sentidos del círculo.", "Incluye vivienda, trabajo o seguridad social.", "Diferencia atención individual de políticas de inclusión sin excluir la primera."]),
  w("caso-externacion", "u2", rights, [58, 61], "case-study", "Caso ficticio: una persona podría continuar su atención fuera del hospital, pero no tiene vivienda ni ingresos. El equipo propone prolongar la internación hasta que 'se arregle sola'. Analizá la situación desde el apartado de derechos sociales.", "El caso muestra una barrera social a la externación. Corresponde pensar apoyos y coordinación entre salud, vivienda, trabajo y protección social, con participación de la persona. El problema no se resuelve atribuyéndolo únicamente a una supuesta incapacidad individual.", ["Identifica la falta de derechos y apoyos como barrera.", "Propone articulación intersectorial concreta.", "Incluye autonomía y participación de la persona; no receta una conducta clínica."]),
  w("caso-fragmentacion", "u2", state, [52, 54], "case-study", "Caso ficticio: una persona repite estudios porque los efectores de distintos subsistemas no comparten información ni coordinan derivaciones. ¿Qué problema expresa y qué dimensiones de mejora considerarías?", "Expresa fragmentación y falta de articulación. Se pueden proponer mecanismos de coordinación y continuidad, responsabilidades claras y circuitos de referencia, contemplando acceso y equidad. La propuesta debe reconocer las diferentes reglas, recursos y actores de los subsistemas.", ["Identifica fragmentación.", "Relaciona duplicaciones con eficiencia y continuidad.", "Propone coordinación sin suponer que los subsistemas son idénticos."]),
  w("caso-at", "u2", rights, [43, 44], "case-study", "Caso ficticio: una familia pide a un AT que asuma solo todas las decisiones terapéuticas y que no informe al equipo. Respondé desde el rol descripto en el PDF.", "El rol exige integración al equipo, coordinación con profesionales tratantes, confidencialidad y comunicación profesional sobre la evolución. La cercanía cotidiana no convierte al AT en sustituto aislado de todo el tratamiento. Debe delimitar responsabilidades y sostener un encuadre profesional.", ["Ubica al AT en el marco interdisciplinario.", "Distingue cercanía de sustitución del equipo.", "Incluye comunicación, confidencialidad y límites profesionales."]),
  w("oral-aps", "u2", rights, [55, 57], "flashcard", "Distinguí en voz alta APS como estrategia, como nivel y como programa de actividades.", "Estrategia: orienta el sistema según acceso y necesidades. Nivel: primer contacto o puerta de entrada. Programa: conjunto de acciones de promoción, prevención, atención y rehabilitación con alcance poblacional y equidad.", ["Distingue las tres perspectivas.", "No reduce toda la APS al primer nivel."]),
  w("oral-at", "u2", rights, [49, 51], "flashcard", "¿Por qué el AT puede ser un puente entre lo clínico y lo comunitario, según Pulice?", "Interviene en escenas cotidianas con una orientación terapéutica singular y sostiene vínculos hacia redes y espacios sociales. Puede favorecer autonomía e inclusión y apoyar tanto a la persona como a su entorno, en articulación con el equipo.", ["Relaciona vínculo singular y vida cotidiana.", "Incluye autonomía, redes y trabajo con el equipo."])
];

const unit3: Question[] = [
  c("examen-preliminar", "u3", diagnosis, [62, 64], "¿Cuál es una tarea central del examen preliminar de la comunidad?", ["Aplicar un tratamiento idéntico a cada habitante", "Revisar críticamente información existente y reconocer necesidades y recursos", "Cerrar el diagnóstico sin contacto con la comunidad", "Evaluar resultados de un programa que todavía no se diseñó"], 1, "El examen preliminar ofrece un primer conocimiento de características, necesidades y recursos a partir de datos disponibles. Orienta prioridades para profundizar el diagnóstico."),
  c("analitico", "u3", diagnosis, [64, 65], "Un diagnóstico busca asociaciones entre desempleo y desmoralización. ¿Qué componente predomina?", ["Exclusivamente descriptivo", "Presupuestario", "Analítico", "Un trámite de derivación"], 2, "El componente analítico estudia asociaciones y posibles determinantes. El descriptivo caracteriza frecuencia y distribución; un diagnóstico mixto combina ambos."),
  c("incidencia", "u3", epi, [69, 70], "¿Qué distingue a la incidencia de la prevalencia en el resumen?", ["Incidencia: casos nuevos en un período; prevalencia: casos existentes en un momento", "Incidencia: todos los casos históricos; prevalencia: solo muertes", "Son nombres intercambiables para cualquier número absoluto", "Prevalencia: casos nuevos; incidencia: casos existentes"], 0, "La incidencia se refiere a casos nuevos durante un período. La prevalencia describe casos existentes en un momento; para compararlas hay que precisar población y referencia temporal."),
  c("cohorte", "u3", epi, [71, 71], "Se forman grupos según exposición laboral y se observa hacia adelante la aparición de un problema. ¿Qué diseño corresponde?", ["Serie de casos", "Corte transversal", "Casos y controles", "Cohorte"], 3, "La cohorte parte de la exposición y sigue la aparición del efecto. En casos y controles se parte de la presencia o ausencia de enfermedad y se indaga exposición previa."),
  c("casos-controles", "u3", epi, [71, 71], "Se seleccionan personas con y sin una enfermedad y se investiga su exposición previa. ¿Qué diseño ilustra?", ["Ensayo comunitario", "Casos y controles", "Cohorte definida por exposición", "Intervención experimental asignada"], 1, "El criterio de conformación de los grupos es la enfermedad. La indagación retrospectiva sobre exposición corresponde al esquema de casos y controles presentado."),
  c("etnografia", "u3", diagnosis, [66, 68], "¿Qué aporta la etnografía al diagnóstico comunitario?", ["Sustituye toda medición por opiniones aisladas", "Garantiza resultados idénticos en todas las culturas", "Permite comprender significados, prácticas y relaciones desde el contexto local", "Elimina la necesidad de participación de usuarios"], 2, "La etnografía usa observación, entrevistas e informantes clave para contextualizar los patrones cuantitativos, comprender prioridades y examinar la congruencia cultural de las intervenciones."),
  t("transversal-causal", "u3", epi, [70, 71], "Un estudio transversal describe enfermedad y exposición en un momento determinado; esa descripción por sí sola no establece la secuencia causal.", true, "El corte transversal es útil para describir prevalencia y planificar. Su medición en un momento no ofrece por sí misma el seguimiento temporal de una cohorte ni la intervención de un experimento."),
  t("redes-siempre", "u3", diagnosis, [66, 67], "Las redes sociales son siempre protectoras, independientemente de cómo sean sus interacciones.", false, "Las redes pueden brindar apoyo emocional e instrumental, pero también contener interacciones negativas. Importa analizar su calidad y sus relaciones de poder."),
  t("critica-cuantitativo", "u3", epi, [72, 74], "La epidemiología crítica exige descartar toda técnica cuantitativa.", false, "La propuesta es integrar técnicas extensivas y cualitativas intensivas, junto con análisis microsociales y macrosociales. La crítica se dirige a la reducción del problema a variables aisladas."),
  w("diagnostico-metodos", "u3", diagnosis, [62, 68], "development", "Diseñá un diagnóstico comunitario inicial que articule información epidemiológica y aproximación cualitativa.", "Primero se revisa información existente sobre población, necesidades y recursos. Luego se profundiza con definición del problema y su distribución, junto con entrevistas, observación y participación comunitaria. La integración permite reconocer magnitud, determinantes, significados y barreras, cuidando la confidencialidad.", ["Diferencia revisión preliminar y profundización del diagnóstico.", "Incluye datos cuantitativos y técnicas cualitativas pertinentes.", "Integra participación y confidencialidad."]),
  w("critica-riesgo", "u3", epi, [75, 76], "development", "Explicá la crítica de Breilh al factor de riesgo aislado y su propuesta de procesos protectores y destructivos.", "El factor aislado puede describir asociaciones sin explicar la reproducción social que las genera. La propuesta crítica estudia procesos continuos y contradictorios vinculados con clase, género y etnia, que producen protección o desgaste. No basta con culpabilizar conductas individuales.", ["Distingue asociación empírica y explicación de procesos.", "Incluye procesos protectores y destructivos.", "Relaciona clase, género y etnia con reproducción social."]),
  w("disenos", "u3", epi, [70, 71], "development", "Compará corte transversal, cohorte, casos y controles y estudio experimental.", "El transversal mide en un momento; la cohorte parte de exposición y sigue efectos; casos y controles parte de enfermedad e indaga exposición previa. En el experimental el investigador interviene sobre la exposición. El diseño elegido condiciona las preguntas y las inferencias posibles.", ["Identifica cómo se forman los grupos o se observa cada diseño.", "Diferencia temporalidad.", "Señala la intervención del investigador como rasgo experimental."]),
  w("caso-conteos", "u3", epi, [65, 70], "case-study", "Ejercicio con datos ficticios: el barrio A tiene 40 casos existentes entre 400 habitantes y B tiene 60 entre 1.200, medidos el mismo día. Calculá las proporciones y explicá por qué no alcanza comparar 40 con 60.", "A: 40/400 = 10 %. B: 60/1.200 = 5 %. B tiene más casos absolutos, pero A tiene mayor proporción de casos existentes. La comparación necesita denominadores y un período o momento definido; aquí se describe prevalencia, no casos nuevos.", ["Calcula 10 % y 5 %.", "Distingue cantidad absoluta y proporción.", "Identifica prevalencia por tratarse de casos existentes en un momento."]),
  w("caso-adherencia", "u3", diagnosis, [66, 68], "case-study", "Caso ficticio: una encuesta informa baja asistencia y el equipo concluye 'ignorancia'. Entrevistas posteriores muestran maltrato en recepción y horarios incompatibles. ¿Qué cambió al incorporar métodos cualitativos?", "Las entrevistas muestran barreras organizativas y relaciones que el dato agregado no explicaba. Ayudan a comprender el punto de vista local y evitan atribuir el comportamiento exclusivamente a características personales. Ambas fuentes deben integrarse para rediseñar la intervención.", ["Reconoce barreras institucionales.", "Explica complementariedad metodológica.", "Propone una consecuencia para la intervención."]),
  w("oral-persona-tiempo", "u3", epi, [65, 70], "flashcard", "¿Qué preguntas básicas organizan la descripción epidemiológica?", "Cuánto ocurre, en quiénes, dónde y cuándo: frecuencia, características de las personas, lugar y tiempo. Para interpretar magnitud se necesita una población de referencia, además de contar casos.", ["Incluye persona, lugar, tiempo y frecuencia.", "Reconoce la necesidad del denominador."]),
  w("oral-matriz", "u3", epi, [73, 76], "flashcard", "Nombrá las tres categorías de la matriz de inequidad de Breilh y explicá por qué no son solo etiquetas personales.", "Clase social, género y etnia. Permiten examinar relaciones de producción, poder y dominación que distribuyen de forma desigual procesos protectores y destructivos.", ["Nombra las tres categorías.", "Las conecta con relaciones estructurales, no con rasgos individuales aislados."]),
  { ...w("imagen-prevalencia", "u3", epi, [65, 70], "image-analysis", "Leé el gráfico de datos ficticios. ¿Qué barrio tiene mayor prevalencia y qué error cometeríamos si miráramos solo el número de casos?", "A presenta 40/400 = 10 % y B 60/1.200 = 5 %. El número absoluto mayor de B no implica mayor prevalencia. Tampoco el gráfico identifica causas: muestra una comparación descriptiva en el mismo momento.", ["Usa los denominadores y obtiene 10 % y 5 %.", "Identifica mayor prevalencia en A.", "No infiere causalidad del gráfico."]), media: { type: "image", src: "/images/sani-prevalencia.svg", alt: "Datos ficticios de casos existentes el mismo día: barrio A, 40 casos en 400 habitantes; barrio B, 60 casos en 1.200 habitantes. Barras de cantidad de casos.", width: 900, height: 540, caption: "Datos inventados para practicar denominadores. No son estadísticas del PDF ni de una población real." } }
];

const unit4: Question[] = [
  c("lalonde", "u4", promotion, [78, 78], "¿Qué cuatro componentes del campo de la salud presenta el Informe Lalonde en el resumen?", ["Diagnóstico, medicación, internación y alta", "Individuo, pareja, familia y escuela", "Biología humana, ambiente, estilos de vida y organización de la atención", "Estado, justicia, policía y mercado"], 2, "La propuesta amplía la explicación de salud más allá de los servicios de atención e incorpora biología, ambiente y estilos de vida."),
  c("ottawa", "u4", promotion, [79, 80], "¿Qué intervención corresponde a la reorientación de los servicios, uno de los campos de Ottawa?", ["Mantener toda la actividad centrada exclusivamente en curar", "Reorganizar el servicio para incorporar promoción, participación y necesidades comunitarias", "Transferir toda responsabilidad a cada usuario", "Aumentar publicidad sin modificar la atención"], 1, "Reorientar los servicios significa revisar su organización y prioridades en relación con promoción de la salud y necesidades de la población, dentro de las cinco líneas de Ottawa."),
  c("prevencion-secundaria", "u4", promotion, [79, 79], "Una acción busca detectar tempranamente un problema y ofrecer atención oportuna para evitar su progresión. ¿Qué nivel de prevención representa?", ["Primaria", "Terciaria", "Ningún nivel de prevención", "Secundaria"], 3, "La prevención secundaria se centra en detección precoz y atención oportuna. La primaria actúa antes de la aparición y la terciaria sobre secuelas y rehabilitación."),
  c("medicar-medicalizar", "u4", community, [85, 87], "En la crítica de Carpintero, ¿qué diferencia medicar de medicalizar?", ["Medicar puede ser un recurso terapéutico; medicalizar reduce problemas de la vida a objetos de intervención médica atravesados por intereses sociales y económicos", "Son sinónimos exactos en todo contexto", "Medicalizar significa escuchar el contexto social", "Todo acto de medicación demuestra por sí solo medicalización"], 0, "El texto distingue el uso del fármaco como instrumento de un equipo del proceso social y político de medicalización. Su crítica no convierte automáticamente todo uso terapéutico de medicación en el mismo fenómeno."),
  t("promocion-prevencion", "u4", promotion, [78, 80], "Promoción de la salud y prevención de la enfermedad son expresiones idénticas y tienen siempre el mismo foco.", false, "La promoción apunta a capacidades, control sobre la salud y condiciones de vida; la prevención se orienta a riesgos, aparición, progresión o secuelas de enfermedades. Pueden complementarse, pero no se confunden."),
  t("ottawa-sector", "u4", promotion, [79, 80], "Los prerrequisitos de salud de Ottawa incluyen condiciones como vivienda, educación, ingresos, justicia social y equidad.", true, "Por eso el trabajo no se restringe al sector sanitario y exige responsabilidades compartidas y acciones intersectoriales."),
  t("usuarios-pasivos", "u4", community, [82, 84], "El enfoque comunitario del resumen reserva a los usuarios el papel de receptores pasivos de decisiones profesionales.", false, "Usuarios, familiares y agentes comunitarios son actores con recursos, capacidad de organización y participación en políticas y servicios. Esto contrasta con la pasividad del modelo manicomial."),
  w("ottawa-cinco", "u4", promotion, [79, 80], "development", "Desarrollá los cinco campos de acción de Ottawa y proponé un ejemplo didáctico para dos de ellos.", "Los campos son políticas públicas saludables, ambientes favorables, acción comunitaria, habilidades personales y reorientación de servicios. Por ejemplo, mejorar espacios barriales seguros actúa sobre ambientes; crear decisiones compartidas con organizaciones fortalece acción comunitaria. No se reduce a dar información individual.", ["Enumera los cinco campos.", "Relaciona dos ejemplos con sus campos.", "Explica su complementariedad e intersectorialidad."]),
  w("usuarios-redes", "u4", community, [82, 84], "development", "Explicá cómo los grupos de usuarios, familiares y líderes comunitarios pueden contribuir a la salud mental comunitaria.", "Pueden aportar ayuda mutua, información, apoyo, defensa de derechos y puentes con espacios sociales. Los usuarios pasan a ser actores de su recuperación y de los servicios. Debe considerarse la lucha contra estigma y discriminación y el papel de las instituciones públicas.", ["Reconoce agencia de usuarios y familiares.", "Incluye ayuda mutua y lazos comunitarios.", "Relaciona participación con derechos y reducción del estigma."]),
  w("caso-promocion", "u4", promotion, [79, 81], "case-study", "Caso ficticio: una campaña de 'vida saludable' solo reparte consejos, pero el barrio carece de espacios seguros y sus vecinos no participan del diseño. Reformulala con Ottawa.", "Se pueden combinar mejoras en ambientes y políticas públicas, decisiones con organizaciones barriales, desarrollo de habilidades y adaptación de servicios. Los consejos individuales son una parte posible, pero no sustituyen condiciones materiales ni capacidad comunitaria de decidir.", ["Identifica los límites de informar sin modificar condiciones.", "Propone al menos tres campos de Ottawa aplicados al caso.", "Incluye participación real."]),
  w("caso-medicalizacion", "u4", community, [85, 87], "case-study", "Caso ficticio para análisis conceptual: una campaña comercial presenta toda tristeza cotidiana como una enfermedad y ofrece una solución única. Analizá la crítica que permitiría formular el texto de Carpintero.", "La crítica examinaría cómo experiencias diversas se convierten en categorías homogéneas de enfermedad, dejando fuera la singularidad y el contexto y favoreciendo intereses comerciales. Debe distinguirse este análisis de negar el padecimiento o de decidir si una persona necesita tratamiento: el caso no aporta una evaluación clínica.", ["Relaciona medicalización con intereses y contexto.", "Reconoce la singularidad del padecimiento.", "Distingue crítica social de una indicación clínica o rechazo de toda medicación."]),
  w("oral-prevencion", "u4", promotion, [79, 79], "flashcard", "Explicá en voz alta prevención primaria, secundaria y terciaria con un ejemplo de objetivo para cada una.", "Primaria: evitar aparición de enfermedad. Secundaria: detectar tempranamente y atender oportunamente. Terciaria: reducir secuelas y favorecer rehabilitación. Son niveles preventivos, no equivalentes a los niveles de complejidad de los servicios.", ["Distingue los tres objetivos.", "No los confunde con primer, segundo y tercer nivel de atención."]),
  w("oral-caracas", "u4", community, [82, 84], "flashcard", "¿Qué orientación atribuye el resumen a la Declaración de Caracas y qué lugar da a la comunidad?", "Promueve reestructurar la atención psiquiátrica vinculándola a la APS y a alternativas comunitarias. El cambio implica revisar la centralidad del hospital psiquiátrico y reconocer recursos y participación de usuarios, familiares y comunidad.", ["Relaciona reforma, APS y comunidad.", "Incluye participación y recursos comunitarios."]),
  { ...w("imagen-ottawa", "u4", promotion, [79, 80], "image-analysis", "El esquema propone cinco acciones para un barrio. Asociá cada letra con uno de los campos de Ottawa.", "A: políticas públicas saludables; B: ambientes favorables; C: acción comunitaria; D: habilidades personales; E: reorientación de servicios. El conjunto articula cambios en condiciones, capacidades, participación y organización de la atención.", ["Relaciona las cinco acciones con los campos.", "Explica por qué el conjunto supera la información individual aislada."]), media: { type: "image", src: "/images/sani-ottawa.svg", alt: "Acciones didácticas: A, política de vivienda saludable; B, espacios públicos seguros; C, consejo barrial con poder de decisión; D, talleres para desarrollar capacidades; E, servicio de salud reorganizado con la comunidad.", width: 900, height: 600, caption: "Ejemplos didácticos inspirados en Ottawa; no es una figura del PDF." } }
];

const unit5: Question[] = [
  c("creencias-salud", "u5", intervention, [89, 90], "¿Qué dimensiones del Modelo de Creencias de Salud enumera el resumen?", ["Susceptibilidad, severidad, beneficios y barreras percibidas", "Solo ingreso, ocupación y escolaridad", "Solo capacidades biológicas objetivas", "Únicamente el conocimiento del diagnóstico"], 0, "El modelo incluye esas cuatro percepciones y relaciona el comportamiento con el valor de un objetivo y la expectativa de alcanzarlo mediante una acción."),
  c("bleger", "u5", intervention, [93, 94], "En el apartado de Videla, ¿qué rol se atribuye al psicólogo desde Bleger?", ["Curar por sí solo a toda la comunidad", "Convertir cada problema social en diagnóstico individual", "Facilitar organizaciones para el cambio desde la psicohigiene y la salud pública", "Limitarse exclusivamente al consultorio privado"], 2, "La función se amplía hacia la salud pública, la prevención y la facilitación de organizaciones para el cambio, en lugar de imaginar al profesional como único agente que cura a la comunidad."),
  c("participacion-plp", "u5", planning, [95, 96], "¿Qué expresa participación en la Programación Local Participativa?", ["Usar a los vecinos como mano de obra de un proyecto decidido por técnicos", "Capacidad real de intervenir en las decisiones como un derecho", "Informar resultados cuando ya no pueden modificarse", "Delegar toda responsabilidad estatal en voluntarios"], 1, "La PLP vincula participación con capacidad decisoria, información, comunicación y valorización del conocimiento popular. No equivale a usar trabajo local para ejecutar decisiones ajenas."),
  c("plan-programa-proyecto", "u5", planning, [99, 99], "¿Cuál es el orden de mayor a menor escala operativa?", ["Proyecto, plan, programa", "Programa, proyecto, plan", "Todos tienen idéntica escala", "Plan, programa, proyecto"], 3, "El plan ofrece el marco técnico-político; el programa organiza procesos con un objetivo; el proyecto concreta actividades, metas, tiempos y recursos en un ámbito acotado."),
  c("momento-estrategico", "u5", planning, [100, 103], "¿Qué pregunta caracteriza al momento estratégico?", ["¿Cómo articular lo que debe hacerse con lo que puede hacerse, construyendo viabilidad?", "¿Cómo ejecutar sin considerar actores?", "¿Cómo fijar objetivos sin negociación?", "¿Cómo describir únicamente cuántos casos existen?"], 0, "El momento estratégico examina viabilidad social, técnica, económica y política, incluyendo actores, poder, acuerdos y conflictos."),
  c("indicador-eficiencia", "u5", planning, [105, 106], "Un indicador relaciona logros de un programa con recursos utilizados. ¿Qué dimensión evalúa?", ["Exclusivamente eficacia", "Solo reconocimiento jurídico", "Eficiencia", "Únicamente diagnóstico inicial"], 2, "Eficiencia relaciona logros y recursos. Eficacia se refiere al grado de cumplimiento del objetivo; calidad examina atributos del servicio, y economía la administración de recursos financieros."),
  c("foda", "u5", planning, [101, 101], "¿Qué asociación corresponde a la matriz FODA?", ["Fortalezas y amenazas internas; oportunidades y debilidades externas", "Fortalezas y debilidades internas; oportunidades y amenazas externas", "Las cuatro categorías describen exclusivamente al entorno", "Las cuatro categorías son sinónimos de objetivos"], 1, "FODA distingue factores internos de la organización o comunidad y factores externos del entorno, según favorezcan u obstaculicen los objetivos."),
  c("evaluacion-proceso", "u5", planning, [101, 107], "Un equipo revisa periódicamente la ejecución y corrige dificultades mientras el programa funciona. ¿Qué evaluación está realizando?", ["Solo evaluación final", "Únicamente evaluación ex ante", "Solo evaluación de impacto a largo plazo", "Evaluación de proceso o monitoreo"], 3, "El monitoreo acompaña la implementación para detectar y corregir problemas. Se distingue de la evaluación previa y de la evaluación de resultados al cierre."),
  t("estilos-contexto", "u5", intervention, [89, 90], "Según Morales Calatayud en el resumen, estudiar hábitos aislados del contexto social puede limitar las intervenciones de promoción.", true, "Los estilos de vida forman parte de un conjunto de relaciones y condiciones. Cambiar conductas específicas sin considerar esa totalidad puede empobrecer la intervención."),
  t("objetivo-actividad", "u5", planning, [104, 106], "'Realizar tres talleres' y 'mejorar un resultado de salud' expresan necesariamente el mismo tipo de componente de un proyecto.", false, "El taller es una actividad o medio. El objetivo expresa el resultado buscado. Las metas precisan cuánto, dónde y cuándo, y los indicadores cómo se medirá."),
  t("estrategica-incertidumbre", "u5", planning, [98, 103], "La planificación estratégica considera al planificador parte de la realidad y reconoce incertidumbre y diversidad de actores.", true, "Por eso la planificación requiere acuerdos, análisis de poder, seguimiento y ajustes; no presupone control técnico completo desde fuera de la situación."),
  w("psicologia-hospital", "u5", intervention, [88, 91], "development", "Describí los dos planos de integración de la Psicología en salud y las cuatro direcciones de trabajo hospitalario del resumen.", "En el plano general participa en políticas, programas y formación; en el particular, en servicios e instituciones. En hospitales se distinguen asistencia a pacientes y familiares, docencia, investigación y acción institucional. Esto amplía el rol más allá de la consulta individual.", ["Distingue planos general y particular.", "Enumera las cuatro direcciones hospitalarias.", "Ilustra una intervención institucional o de programas."]),
  w("comparar-planificacion", "u5", planning, [98, 103], "development", "Compará planificación normativa y estratégica respecto del planificador, el poder y la incertidumbre.", "La normativa presupone un planificador externo con control técnico, secuencias más lineales y énfasis en lo deseable. La estratégica reconoce al planificador como actor situado, otros intereses y poderes, incertidumbre y necesidad de viabilidad. Sus momentos se articulan dinámicamente.", ["Contrasta posición del planificador.", "Incluye poder, negociación e incertidumbre.", "Distingue etapas rígidas de momentos articulados."]),
  w("plp-pasos", "u5", planning, [95, 97], "development", "Reconstruí los seis pasos de la Programación Local Participativa y explicá qué se produce en cada uno.", "Se analizan problemas y explicaciones; se definen objetivos; se identifican actividades; se calculan recursos y fuentes; se fijan tiempos y responsables; y se evalúan logros frente a lo esperado. La participación, la flexibilidad y la discusión comunitaria dan sentido al procedimiento.", ["Ordena los seis pasos.", "Distingue objetivos, actividades y recursos.", "Incluye tiempos, responsables y evaluación participativa."]),
  w("caso-plan", "u5", planning, [104, 107], "case-study", "Caso ficticio: un barrio identifica barreras de acceso a sus servicios. Formulá un problema delimitado, un objetivo, una meta, una actividad y un indicador coherentes. Los números que propongas deben indicarse como hipotéticos.", "Una respuesta puede delimitar dificultades de acceso en una población y período; proponer reducir una barrera; fijar una mejora medible y temporal como meta hipotética; acordar horarios como actividad; y medir la proporción de usuarios que logra atención. El diagnóstico real debe establecer línea de base y viabilidad antes de fijar compromisos.", ["No confunde el problema con la falta de una solución predeterminada.", "Mantiene coherencia entre objetivo, meta, actividad e indicador.", "Aclara población, tiempo y carácter hipotético de los valores.", "Incluye participación y verificación de recursos."]),
  w("caso-viabilidad", "u5", planning, [100, 103], "case-study", "Caso ficticio: un proyecto tiene presupuesto y respaldo técnico, pero usuarios y organizaciones se oponen porque no fueron escuchados. ¿Es suficiente considerarlo viable?", "No. La viabilidad económica y técnica no reemplaza la social y política. Habría que reconocer actores, intereses, poder y motivos de oposición, abrir participación y negociar cambios, en lugar de interpretar el desacuerdo como un obstáculo que se elimina solo con información.", ["Distingue dimensiones de viabilidad.", "Incluye análisis de actores y relaciones de poder.", "Propone participación y negociación sobre el proyecto."]),
  w("caso-etica", "u5", intervention, [92, 94], "case-study", "Caso ficticio: un profesional decide por el barrio y vuelve indispensable su presencia para toda actividad. ¿Qué principios del apartado de Videla permiten revisar su intervención?", "La intervención debe evitar fomentar dependencia, trabajar en equipo y facilitar organización y autonomía. La crítica a psicologizar problemas sociales invita a analizar condiciones y no a convertir al profesional en solución única. La educación popular aporta diálogo y conciencia crítica.", ["Identifica dependencia y verticalismo.", "Propone trabajo en equipo y fortalecimiento comunitario.", "Relaciona intervención con contexto social y autonomía."]),
  w("oral-matus", "u5", planning, [99, 103], "flashcard", "Relacioná los cuatro momentos de Matus con explicar, diseñar lo deseado, construir viabilidad y hacer.", "Explicativo: qué fue, es y tiende a ser. Normativo: qué debe ser. Estratégico: relación entre debe ser y puede ser. Táctico-operacional: hacer, gestionar y evaluar. Son momentos enlazados, no compartimentos rígidos.", ["Relaciona correctamente los cuatro momentos.", "Reconoce su articulación dinámica."]),
  w("oral-objetivos", "u5", planning, [105, 106], "flashcard", "Diferenciá objetivo, meta, actividad e indicador en una respuesta breve.", "Objetivo: resultado que se busca. Meta: cuánto se espera lograr, dónde y cuándo. Actividad: qué se hará para alcanzarlo. Indicador: señal o medida utilizada para observar el objetivo. Una actividad realizada no prueba por sí sola que se logró el resultado.", ["Distingue los cuatro componentes.", "No equipara cumplimiento de actividades con logro del objetivo."]),
  { ...w("imagen-arbol", "u5", planning, [99, 104], "image-analysis", "En este árbol de problemas ficticio, identificá causas, problema central y efectos. Proponé una pregunta para validar el árbol con la comunidad.", "Las raíces representan horarios incompatibles y transporte costoso; el tronco, dificultades de acceso a turnos; las ramas, demoras y discontinuidad de atención. Son relaciones hipotéticas que deben contrastarse con datos y voces locales. Una pregunta posible: ¿qué barreras aparecen en sus experiencias y cuáles faltan en el esquema?", ["Identifica raíces, tronco y ramas.", "Reconoce que las relaciones necesitan validación.", "Propone una pregunta abierta que incluya la perspectiva comunitaria."]), media: { type: "image", src: "/images/sani-arbol.svg", alt: "Árbol de un caso ficticio: arriba, demoras y discontinuidad de atención; en el centro, dificultades para acceder a turnos; abajo, horarios incompatibles y transporte costoso.", width: 900, height: 540, caption: "Árbol didáctico de un caso ficticio. No es un diagnóstico realizado ni una figura del resumen." } }
];

const finalQuestions: Question[] = [
  w("final-determinacion", "u1", integration, [1, 20], "development", "Integrá salud colectiva, determinantes sociales e interdisciplina: ¿por qué no alcanza un enfoque exclusivamente individual?", "El proceso colectivo articula condiciones estructurales, vida cotidiana y subjetividad. Los hábitos no están aislados de recursos, relaciones y poder. La complejidad exige aportes disciplinarios compartidos y acciones intersectoriales con participación y equidad.", ["Relaciona dimensiones y niveles de determinación.", "Explica límites del individualismo.", "Deriva estrategias interdisciplinarias e intersectoriales."]),
  w("final-derechos", "u2", integration, [40, 61], "case-study", "Caso integrador ficticio: un programa de externación ofrece consultas, pero ignora vivienda, ingresos y discriminación. Explicá qué falta desde derechos, APS y acompañamiento terapéutico.", "Las consultas pueden ser necesarias pero no resuelven por sí solas barreras de inclusión. Hace falta una red que articule salud y otros sectores, apoyos cotidianos, participación de usuarios y condiciones de vida. El AT puede colaborar como puente con redes, sin reemplazar políticas sociales ni al equipo.", ["Distingue asistencia e inclusión social.", "Integra derechos, APS y trabajo intersectorial.", "Ubica al AT dentro de una red y una estrategia."]),
  w("final-diagnostico", "u3", integration, [62, 77], "development", "¿Cómo articularías diagnóstico epidemiológico, etnografía y epidemiología crítica en el análisis de una desigualdad de salud?", "La descripción caracteriza frecuencia y distribución; la etnografía permite comprender experiencias, significados y barreras; la mirada crítica examina procesos de reproducción social y relaciones de clase, género y etnia. Se integran métodos para explicar y actuar, evitando confundir asociación con explicación suficiente.", ["Asigna un aporte específico a cada aproximación.", "Articula técnicas cuantitativas y cualitativas.", "Relaciona desigualdades con procesos estructurales."]),
  w("final-promocion", "u4", integration, [78, 87], "case-study", "Caso integrador ficticio: una política llama 'promoción de salud mental' a una campaña que etiqueta malestares cotidianos y ofrece una única respuesta individual. Contrastala con Ottawa, participación y la crítica a la medicalización.", "Se debe revisar si la propuesta amplía control comunitario, capacidades y condiciones de vida o solo convierte experiencias en demandas individuales. Ottawa orienta a políticas, ambientes, acción comunitaria, habilidades y servicios. La crítica a medicalización considera contexto e intereses sin negar atención a quien la necesita.", ["Distingue promoción de una respuesta individual única.", "Integra campos de Ottawa y participación.", "Atribuye la crítica al marco del texto y evita indicaciones clínicas."]),
  w("final-proyecto", "u5", integration, [95, 107], "development", "Defendé un proyecto comunitario hipotético: diagnóstico, prioridad, objetivo, meta, actividades, actores, recursos y evaluación. Justificá su coherencia.", "El proyecto debe partir de un problema reconocido con la comunidad, priorizado mediante criterios explícitos. Objetivos y metas orientan actividades, recursos, responsabilidades e indicadores. La viabilidad requiere negociación entre actores y una evaluación que permita ajustar el proceso y contrastar resultados con la línea de base.", ["Deriva el proyecto de un diagnóstico participativo.", "Mantiene coherencia entre resultados buscados y acciones.", "Incluye poder, recursos, tiempos y responsables.", "Diferencia monitoreo y evaluación de resultados."]),
  w("final-oral", "u5", integration, [88, 107], "flashcard", "Ensayá una respuesta de final: ¿qué diferencia a un psicólogo sanitario de un rol limitado a la consulta individual?", "El resumen sitúa al psicólogo en políticas y programas, equipos e instituciones, promoción, prevención, comunidad y planificación. La consulta puede integrar ese trabajo, pero no agota sus competencias. La intervención requiere leer contexto, participar con otros actores y evaluar resultados.", ["Relaciona los planos general e institucional.", "Incluye comunidad, equipos y planificación.", "Sostiene una respuesta articulada, no una lista de palabras."])
].map((question) => ({ ...question, finalOnly: true, difficulty: "Integración" }));

export const saniQuestions: Question[] = [...unit1, ...unit2, ...unit3, ...unit4, ...unit5, ...finalQuestions];
